### ISSUE TITLE
Failed to compile against lpi4a_defconfig

### ISSUE THREAD

**Issue by lone0** [pdp7/linux#3]
Hi Drew,
    In attempting to have a working kernel from mainstream that supports eMMC in lpi4a, I am building the branch ahead-emmc with lpi4a_defconfig. And it stops here:

make[7]: *** No rule to make target '/lib/firmware/rtw88/rtw8723d_fw.bin', needed by 'drivers/base/firmware_loader/builtin/rtw88
/rtw8723d_fw.bin.gen.o'.  Stop.
make[7]: *** Waiting for unfinished jobs....

    Any suggestions?
.

**Comment by lone0** [comment]
Alright, forget about lpi4a_defconfig. To boot on Lichee Pi 4A all you need is the defconfig with one line in addition:

@@ -168,6 +168,7 @@
 CONFIG_MMC_SDHCI=y
 CONFIG_MMC_SDHCI_PLTFM=y
 CONFIG_MMC_SDHCI_CADENCE=y
+CONFIG_MMC_SDHCI_OF_DWCMSHC=y
 CONFIG_MMC_SPI=y
 CONFIG_MMC_SUNXI=y
 CONFIG_RTC_CLASS=y

**Comment by pdp7** [comment]
@lone0 thank you for the update.  I do have a LPi4 and I need to start incorporating it into my testing going forward.
